[project]
name = "hackathon-whatsapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "rich>=13.9.4",
    "ruff>=0.11.2",
    "twilio>=9.5.1",
]
